### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Victor239** [flathub/com.borgbase.Vorta#140]
Flathub allows changelogs for each new release - can these be automated?

**Comment by real-yfprojects** [comment]
I didn't find any documentation on changelogs.

**Comment by Victor239** [comment]
Changelogs can be displayed on Flathub and within distro app updaters, all that's needed is an `.appdata`/[.metainfo.xml](https://docs.flatpak.org/en/latest/conventions.html#appdata-files) file. 

See these examples of another app's [appdata.xml](https://github.com/flathub/io.github.trigg.discover_overlay/blob/master/io.github.trigg.discover_overlay.appdata.xml), and how their changelog is [displayed on Flathub](https://flathub.org/en-GB/apps/io.github.trigg.discover_overlay).

**Comment by Hofer-Julian** [comment]
Yeah, we'd have to update https://github.com/borgbase/vorta/blob/master/src/vorta/assets/metadata/com.borgbase.Vorta.appdata.xml#L42 during the release process. Is this something you'd be fine with @m3nu?

**Comment by m3nu** [comment]
I can add it to the release process. With the macOS release being built on Github, we are close to anyone being able to do the release. Would just need an extra account on Pypi, I think.

For Flatpak, this would be the relevant part? I already write this up for Github releases.

```
  <releases>
    <release version="0.6.7" date="2023-09-24" urgency="low">
      <description>
        <ul>
          <li>Made overlays give up Gamescope XAtom when no content is present</li>
          <li>Added Reset buttons to each config page</li>
          <li>Fix issue where multiple monitors with the same name exist</li>
          <li>Catch invalid guild id crashes</li>
          <li>Hide voice overlay on unexpected disconnect</li>
          <li>Fixed some broken translations</li>
        </ul>
      </description>
    </release>
```

**Comment by Hofer-Julian** [comment]
@m3nu looks good!

Will close this issue then

**Comment by m3nu** [comment]
Added those release logs for the latest v0.9.1-beta2 release:

https://github.com/borgbase/vorta/releases/tag/v0.9.1-beta2
