### ISSUE TITLE
Why is org.freedesktop.Flatpak required?

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.borgbase.Vorta#145]
This was added in https://github.com/flathub/com.borgbase.Vorta/commit/6ab59939cd6e4e243f62986f1b6fe33f2b55f08e what does it need for mounting?

**Comment by Hofer-Julian** [comment]
I honestly can't remember. Feel free to remove it in a PR and see if it still works

**Comment by real-yfprojects** [comment]
> I honestly can't remember

A more detailed commit message could have prevented this :)

**Comment by Hofer-Julian** [comment]
It's needed for running fuse mount via flatpak spawn on the host.
