### ISSUE TITLE
Remove org.kde.* permission

### ISSUE THREAD

**Issue by bilelmoussaoui** [flathub/com.borgbase.Vorta#19]
The app shouldn’t have the possibility to own any dbus name under org.kde.*

**Comment by Hofer-Julian** [comment]
I'd very much like to have a different solution. As you can see here https://github.com/flathub/com.borgbase.Vorta/commit/d4d45e2e0c75ae1a5e86f809e12dbc7a161983e4 it originally had different permissions to allow to display the status icon. But I couldn't find a set of permissions which works all the time, apart from the current one.

What I found surprising as well, is that the status icon is broken for most flatpaks, but some of them have a comment in the issues by @TingPing that one can manually override this option if one wants to have a status icon.

**Comment by TingPing** [comment]
The different solution means patching Qt. Probably just going to have to live with it in the short term.

**Comment by Hofer-Julian** [comment]
Thanks for you input @TingPing, I am also looking forward to future improvements in flatpak.

@bilelmoussaoui, okay if I close this issue for now?

**Comment by samuel-w** [comment]
Maybe look at https://github.com/flathub/com.discordapp.Discord/blob/master/com.discordapp.Discord.json.

These lines seem like they might work:
```
    "--env=XDG_CURRENT_DESKTOP=Unity",
    "--talk-name=org.kde.StatusNotifierWatcher",
    "--talk-name=com.canonical.AppMenu.Registrar"
```

**Comment by TingPing** [comment]
Discord doesn't use Qt.

**Comment by samuel-w** [comment]
Here is a package that does use Qt. https://github.com/flathub/org.keepassxc.KeePassXC/blob/master/org.keepassxc.KeePassXC.yml

```
    # System Tray Icon (Test at every major update)
  - --talk-name=org.kde.StatusNotifierWatcher
  - --own-name=org.kde.StatusNotifierItem-2-2 # Especially test this
```

**Comment by TingPing** [comment]
Qt's implementation is simply broken because it cannot rely on `org.kde.StatusNotifierItem-2-2` not being owned.
