### ISSUE TITLE
Error updating appstream2

### ISSUE THREAD

**Issue by carobinario** [flathub/com.borgbase.Vorta#36]
Hi,
I installed Vorta via Flathub. Today I updated it to version 0.7.3 using **Discover** 5.20.5 and started Vorta without any problem.

Now every time I open Discover it display this warning message at the bottom: _Error updating appstream2: No such ref 'appstream2/x86_64' in remote vorta-origin; Error updating appstream 'No such ref 'appstream/x86_64' in remote vorta-origin._

To solve the issue I ran this command: $ flatpak repair --user: unfortunately I still have the warning message.

Of course my system is up to date.
_Error message:_
![appstream-error](https://user-images.githubusercontent.com/16922051/108747698-0a876680-753e-11eb-837b-7d4f499f27c1.png)

_Flatpak repos:_
![flatpak repos](https://user-images.githubusercontent.com/16922051/108747903-46223080-753e-11eb-9f96-52b2da36dc8a.png)

**Operating System:** Fedora 33 Kde spin
**KDE Plasma Version:** 5.20.5
**KDE Frameworks Version:** 5.78.0
**Qt Version:** 5.15.2
**Kernel Version:** 5.10.16-200.fc33.x86_64
**OS Type:** 64-bit
**Graphics Processor:** Mesa Intel® HD Graphics 530

**Comment by Hofer-Julian** [comment]
Sorry, but this sounds like either a problem with Discover or like a broken flatpak installation, rather than a problem with Vorta

**Comment by carobinario** [comment]
Problem found: there were two vorta references on my system, one from flathub stable (vorta), the other one from flathub test (vorta-origin).

```
$ flatpak remotes
Name         Options
fedora       system,oci
flathub      system
vorta-origin user,no-enumerate
```
```
$ flatpak remote-delete vorta-origin
$ flatpak remotes
Name    Options
fedora  system,oci
flathub system

```
Fixed.

**Comment by Hofer-Julian** [comment]
Glad to hear that this fixed your problem 😊
I am surprised though that this was correlated
