### ISSUE TITLE
Update KDE runtime

### ISSUE THREAD

**Issue by Justinzobel** [flathub/com.borgbase.Vorta#42]
KDE Platform 5.15 is out and very stable, are we able to please update?

**Comment by Hofer-Julian** [comment]
Unfortunately 5.15 brought problems with the file picker

**Comment by Justinzobel** [comment]
Ah fair enough. Is there a KDE bugzilla report we can link to so we can track it's fix?

**Comment by Hofer-Julian** [comment]
Not that I would know of
