### ISSUE TITLE
Does not launch on Wayland

### ISSUE THREAD

**Issue by n194** [flathub/com.borgbase.Vorta#50]
On Wayland platforms, Vorta's Flatpak fails to launch.
```shell
> com.borgbase.Vorta
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```

According to [discussion on Vorta's issue tracker](https://github.com/borgbase/vorta/issues/1012#issuecomment-864470989), they recommend using pyqt v5.15.3 or higher to fix this issue.

**Comment by Hofer-Julian** [comment]
Well, it does launch for me with wayland and Fedora 35.
Which distro are you using?

**Comment by n194** [comment]
I'm using Arch Linux. I've only had this issue with the Flatpak release.

**Comment by real-yfprojects** [comment]
The flatpak now uses PyQt `v5.15.7`.

**Comment by n194** [comment]
I don't use Wayland or the Flatpak anymore so I can't check if this is still an issue.
