### ISSUE TITLE
Consider forcing X11 until KDE runtime is >= v5.15

### ISSUE THREAD

**Issue by phihos** [flathub/com.borgbase.Vorta#52]
In [this comment](https://github.com/borgbase/vorta/issues/1023#issuecomment-1003582491) in the Vorta main repo I explained how to fix Vorta's look on Gnome by forcing the use of X11/XWayland. It is installed on most distro by default I think.
The latest KDE runtime (v5.15) seems to fix the theming issue on Wayland + GTK but there is a file chooser bug on Kubuntu preventing an upgrade. So would it be possible at least until then to just force X11 by default? I think this would benefit more users than setting this to Wayland by default.

**Comment by Hofer-Julian** [comment]
We use 5.15 now
