### ISSUE TITLE
Cannot create repo on external HDD

### ISSUE THREAD

**Issue by Split7fire** [flathub/com.borgbase.Vorta#6]
So the problem just as mentioned in title: no external device can be found in "Select backup destination". Seems that flatpak-specific rights needed for vorta to write on external hard drives. Any ideas?

**Comment by Hofer-Julian** [comment]
Vorta has host permissions, it has therefore access to all allowed directories.
Where do you mount your external device?

**Comment by Split7fire** [comment]
Ok, let me clarify some points:
My OS is Fedora 30 Gnome,
My external hdd is just cheap 2.5 inch case with hdd. So, when I plug-in hdd case in PC, hdd filesystem name appear in file manager (named "Files" in Gnome). Next, if I click on it, it will mount on /run/media/{name_of_user}/{name_of_volume}

**Comment by Hofer-Julian** [comment]
I have the exact same setup und just tried it. In my case it works perfectly and I don't really know what could have gone wrong in your case.

**Comment by Split7fire** [comment]
Ok, I figured this out. The problem: if you start vorta **before** attaching hdd drive, you'll see nothing in file manager. But if you first attach external drive, and then start vorta, everything would be perfect. I don't know is it vorta bug or vorta_over_flatpak. Any thoughts?

**Comment by Hofer-Julian** [comment]
Not sure of it's even a bug, are you sure you can't access it or is there only no bookmark?

**Comment by Split7fire** [comment]
@Hofer-Julian, sorry for delay reply. I have no bookmark for this external drive. Maybe, flatpak mount/bind re-enumerate devices only on start? Also, could flatpak portals solve this?

**Comment by Hofer-Julian** [comment]
Ah yes, I forgot about this issue, sorry.
Mounts don't seem to appear when the dir chooser is run as a flatpak, you will have to manually navigate to /run
