### ISSUE TITLE
problems with pre-backup script on vorta flatpak

### ISSUE THREAD

**Issue by sunhasgothishaton** [flathub/com.borgbase.Vorta#66]
Hi @Hofer-Julian 

I'm having a problem getting a pre-backup bash script to work With Vorta flatpak version. This script works when run from a terminal, I'm having problems when called from Vorta flatpak version, it works with vorta pip version.

My script logs several things, mainly packages installed (flatpak, pip, apt).

It seems the problem is that it can't find any of the external commands in /usr/bin (neofetch, flatpak, etc). I have checked $PATH in the script (set by flatpak/Vorta) and its set to /app/bin:/usr/bin

I have used "command -v neofetch", "which neofetch" and called directly "/usr/bin/neofetch" and none of these work to find the external commands.

It also calls another of my scripts which uses the file /var/log/apt/history.log which reports that it doesn't exist (even though it does).

Can you help/suggest what I can do?

**Comment by Hofer-Julian** [comment]
You can try to prepend your commands with `flatpak-spawn --host`

**Comment by sunhasgothishaton** [comment]
Great, that works now.

Thank you for your help.
