### ISSUE TITLE
Issue connecting to repo

### ISSUE THREAD

**Issue by alexpattyn** [flathub/com.borgbase.Vorta#8]
**Issue**
When I go to restore from a backup on an external HDD (haven't tried on the same drive, but that wouldn't make much sense), I can't connect to the repo. I can confirm using borgbackup from fedora 30's repos that I can see and restore from the backup. 

Version from fedora 30
```
$ borg --version
borg 1.1.10
```

This repo was created with vorta. 

**Steps to reproduce**
1) Make a backup with vorta.
2) Disconnect the repo 
3) Select add existing repo.
4) See error "Unable to add your repository"

**Comment by alexpattyn** [comment]
Well I tried making a new repo in vorta and un-linking it then reconnecting and everything is fine. However, the repo I actually care about can not be connected to. So thats rather odd.

**Comment by Hofer-Julian** [comment]
Sorry, that I only reply now.
Unfortunately, I have no idea what the root of your problem might be...

**Comment by alexpattyn** [comment]
Well I haven't been able to replicate this issue. But would validating the backup (under the schedule panel) catch this? i.e. will the user be notified?

But I was able to recover the data from that backup by using borg from the cli. For some reason vorta just couldn't link to it.

**Comment by Hofer-Julian** [comment]
Hard to say, without knowing what the cause was...

I am closing it for now
