### ISSUE TITLE
Extract file from snapshot fail

### ISSUE THREAD

**Issue by jsagfr** [flathub/com.borgbase.Vorta#92]
# Problem

Tested with a local depot only:  When extracting a file from a snapshot, Vorta show the error message:
```
2022-12-21 09:38:47,524 - vorta.borg.borg_job - INFO - Running command /app/bin/borg extract --list --info --log-json /var/home/user/Backup/testvorta::host-2022-12-21-091257 --patterns-from /tmp/tmp3gq8roh4
2022-12-21 09:38:47,865 - vorta.borg.borg_job - WARNING - Error: [Errno 2] No such file or directory: '/tmp/tmp3gq8roh4'
```

And no file was extracted. Mounting the snapshot works.

# Possible explanation

Even with `--filesystem=host`, flatpak does not seem to have to access so `/tmp`. The
[flatpak documentation](https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access) explains:

> * If an application uses `$TMPDIR` to contain lock files you may want to add a wrapper script that sets it to `$XDG_RUNTIME_DIR/app/$FLATPAK_ID`.

# Configuration

## OS

Fedora Linux 37.20221216.0 (Silverblue)

## Flatpak

```bash
[user@host ~]$ flatpak info com.borgbase.Vorta 

Vorta - Backup client

          ID: com.borgbase.Vorta
         Ref: app/com.borgbase.Vorta/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: v0.8.9
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 70,0 Mo
     Runtime: org.kde.Platform/x86_64/5.15-21.08
         Sdk: org.kde.Sdk/x86_64/5.15-21.08

      Commit: b199c45e13d5e1d740b2fdcaeff408ddf82d0e8009065cd6f59cec84a164d784
      Parent: b6bee076c133c209bf8084b5444005e1ab105e91143481b0c1f75bc0e31f114e
     Subject: Update peewee-3.15.3.tar.gz to 3.15.4 (7b1ff6cd)
        Date: 2022-11-13 09:36:05 +0000
```

**Comment by Hofer-Julian** [comment]
Sorry, seems like I missed your issue.
If I understand it correctly, this is the problem `--patterns-from /tmp/tmp3gq8roh4`.
However, this doesn't seem to make problems on my machine (also Fedora Silverblue).

Can you still reproduce the bug?

**Comment by real-yfprojects** [comment]
I think this was fixed upstream already.

**Comment by Hofer-Julian** [comment]
Then let's close it for now :)

**Comment by real-yfprojects** [comment]
> Then let's close it for now :) 

Updated above comment. This is indeed fixed.
