### ISSUE TITLE
How to invoke the borg binary? (specifically for borg check -repair)

### ISSUE THREAD

**Issue by ScrambleTheRamble** [flathub/com.borgbase.Vorta#93]
I'm using the vorta 0.8.9 flatpak for backups and after running a routine check on my archive I noticed several warnings in the log regarding missing chunks. eg:

`2023-01-11 18:56:48,464 - vorta.borg.borg_job - INFO - gigabyte-x570-aorus-ultra-2022-04-29-161028: home/ochal/Pictures/2018/07/15/NIKON D750/DSC_8571.NEF: Completely healed previously damaged file!`

If I'm not mistaking borg check by default doesn't do the actual repairs unless also executed with -repair but vorta runs check without the -repair flag. How can I invoke borg from the CLI with the repair flag without installing the borg binary directly (which might be a different version than the version included in the flatpak)?

**Comment by Hofer-Julian** [comment]
You can run `flatpak run com.borgbase.Vorta --command=sh` to enter the flatpak environment.
There you will have `borg` available.

**Comment by ScrambleTheRamble** [comment]
Aha! TIL :)
